name: test_chat_with_socket
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.4
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  grouped_list: ^6.0.0
  intl: ^0.19.0
  logger: ^2.4.0
  socket_io_client: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
